### ISSUE TITLE
引入vue2工程项目后,setOption一些js的内函数报错提示找不到

### ISSUE THREAD

**Issue by Fnckerpoi** [Aaron-China/vue-cli3#2]
在新建vue工程引用作者的js和vue文件，甘特控件能正常渲染出来并使用。
但是将gantt的vue和两个js文件复制移植到项目中就提示setOption等一些函数not found。
且有发现gantt的js大小为660KB。编译启动的时候会提示超过500KB。
不知道找不到js内的函数问题要如何解决？

**Comment by Aaron-China** [comment]
建议直接使用官方的最新版本，现在好像升级到v10了，我用那会还是v7，官方迭代了很多东西，不过案例的配置项没区别
